### PR TITLE
Fix/brew session without a recipe

### LINKED ISSUE #39: Brews without Recipes crash the dashboard
It is possible to delete a Recipe in GrainFather's app and end up with an orphaned brew session.

### PR DESCRIPTION
**Pull request by hez**
fixes #39

### CODE REVIEW

File: lib/brew_dash_web/live/brew_card_component.ex [hunk 1]
```diff
@@ -6,10 +6,28 @@ defmodule BrewDashWeb.BrewCardComponent do
...
   @default_image "/images/default_brew.jpg"
 
-  def image_url(%Brew{recipe: %Recipe{image_url: nil}}),
+  def image_url(%Brew{recipe: recipe}) when recipe == nil or recipe.image_url == nil,
     do: Routes.static_path(BrewDashWeb.Endpoint, @default_image)
 
   def image_url(%Brew{recipe: %Recipe{image_url: image_url}}), do: image_url
 
-  def show_brew_name?(%Brew{recipe: recipe, name: name}), do: recipe.name != name
+  def display_name(%Brew{} = brew) do
```
Comment (Baradoy) [inline lib/brew_dash_web/live/brew_card_component.ex:14]: This works, but one thing it does is cut us off from the path of having different styles for different section of the display name. 
Eg:
**Folkol**-_Idaho-7_ (_**batch 3**_)

That is fine if we do not care to go down that path. Otherwise I would suggest moving display name into its own component.

**Review by Baradoy — APPROVED** [review]
:+1: 
Left a comment.

File: lib/brew_dash_web/live/brew_card_component.ex (hunk 1 above)
Comment (hez) [reply lib/brew_dash_web/live/brew_card_component.ex:14]: Yeah, I was thinking the same.  I was imagining this would get pulled out somewhere when we want to use it else where or have different displayable names.
